import "./globals.css";

export const metadata = {
  title: "Jadoo App Travel",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500&family=Volkhov:wght@700&display=swap" rel="stylesheet" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
        <meta
          property="og:url"
          content="https://jadoo-app-travel-landing-page.vercel.app/"
        />
        <meta
          property="og:type"
          content="website"
        />
        <meta
          property="og:title"
          content="Jadoo"
        />
        <meta
          property="og:description"
          content="Travel app, life app, aplikasi travel, aplikasi jalan-jalan, pesan guide, dan sebagainya."
        />
        <meta
          property="og:image"
          content="https://jadoo-app-travel-landing-page.vercel.app/aplikasi-travel-online.jpg"
        />
      </head>
      <body>
        {children}
      </body>
    </html>
  );
}
